# constants.py

# Telegram bot token from BotFather
TOKEN = 'YOUR_BOT_TOKEN'

# States for ConversationHandler
(
    LANGUAGE_SELECTION,
    INCOME_AMOUNT,
    INCOME_CURRENCY,
    INCOME_CATEGORY,
    INCOME_COMMENT,
    EXPENSE_AMOUNT,
    EXPENSE_CURRENCY,
    EXPENSE_CATEGORY,
    EXPENSE_COMMENT,
    REPORT_SELECTION,
    REPORT_ACTION_SELECTION,
    GRAPH_REPORT_SELECTION,
    FAMILY_BUDGET_MENU,
    FAMILY_CREATE,
    FAMILY_JOIN,
    FAMILY_BUDGET_ACTIONS,
    FAMILY_BUDGET_SET_AMOUNT,
    SETTINGS_SELECTION,
) = range(18)

# Supported currencies
CURRENCIES = ['USD', 'UZS']
