# language_data.py

languages = {
    'uz': {
        'start_message_new': "Salom! 😃 \nKerakli bo'limni tanlang:",
        'start_message_returning': "Kerakli bo'limni tanlang:",
        'choose_language': "🇺🇿 Iltimos, tilni tanlang:",
        'income': "⬇️Kirim",
        'expense': "⬆️Chiqim",
        'report': "🔄Hisobot",
        'settings': "⚙️Parametr",
        'enter_income_amount': "💴 Kirim summasini kiriting:",
        'enter_expense_amount': "💸 Chiqim summasini kiriting:",
        'choose_currency': "💰 Pul birligini tanlang:",
        'choose_category': "📂 Bo'limni tanlang:",
        'enter_comment': "💬 Kommentariya kiriting:",
        'data_saved': "✅Ma'lumot saqlandi",
        'choose_report': "Qaysi hisobotni ko'rmoqchisiz?",
        'weekly': "Haftalik",
        'monthly': "Oylik",
        'view_in_telegram': "📲Telegramda ko'rish",
        'download': "💾Yuklab olish",
        'report_sent': "✅Hisobot yuborildi",
        'operation_cancelled': "❌Amal bekor qilindi.",
        'incorrect_selection': "Noto'g'ri tanlov.",
        'error_generating_report': "Hisobot yaratishda xatolik yuz berdi.",
        'cancel': "❌Bekor qilish",
        'change_language': "Tilni o'zgartirish",
        'select_language': "Tanlovni bajaring:",
        'invalid_amount': "Iltimos, to'g'ri summa kiriting:",
        'no_data': "Hisobot uchun ma'lumot topilmadi.",
        'expense_categories': [
            ('🩺 Sog\'liqni saqlash', 'Sog\'liqni saqlash'),
            ('🏖️ Dam olish', 'Dam olish'),
            ('💡 Kommunal to\'lovlar', 'Kommunal to\'lovlar'),
            ('💳 Kredit', 'Kredit'),
            ('🍽️ Ovqatlanish', 'Ovqatlanish'),
            ('🎓 Ta\'lim', 'Ta\'lim'),
            ('🎁 Sovg\'alar', 'Sovg\'alar'),
            ('🛒 Oziq-ovqat', 'Oziq-ovqat'),
            ('👨‍👩‍👧‍👦 Oila uchun', 'Oila uchun'),
            ('🏅 Sport', 'Sport'),
            ('🚗 Transport', 'Transport'),
            ('🔧 Boshqalar', 'Boshqalar'),
        ],
        'income_categories': [
            ('💵 Oylik maosh', 'Oylik maosh'),
            ('🎁 Sovg\'a', 'Sovg\'a'),
            ('🏦 Omonat foizlari', 'Omonat foizlari'),
            ('🔧 Boshqalar', 'Boshqalar'),
        ],
        # Yangi qo'shilgan matnlar
        'family_budget': "👨‍👩‍👧‍👦 Oila budjeti",
        'register_family': "👨‍👩‍👧‍👦 Oila yaratish",
        'join_family': "👥 Oilaga qo'shilish",
        'family_member': "👤 Oila a'zosi",
        'approve_expense': "✅ Chiqimni tasdiqlash",
        'reject_expense': "❌ Chiqimni rad etish",
        'expense_approved': "✅ Chiqim tasdiqlandi",
        'expense_rejected': "❌ Chiqim rad etildi",
        'request_sent': "✅ So'rov yuborildi, oila boshlig'i tasdiqlashini kuting.",
        'set_budget': "💰 Byudjet ajratish",
        'enter_budget_amount': "💰 Byudjet summasini kiriting:",
        'budget_set': "✅ Byudjet ajratildi",
        'insufficient_budget': "❌ Byudjet yetarli emas.",
        'graph_report': "📊 Grafik hisobot",
        'select_graph_type': "Grafik turini tanlang:",
        'income_expense_over_time': "📈 Vaqt bo'yicha kirim/chiqim",
        'category_distribution': "📊 Kategoriya bo'yicha taqsimot",
    },
    'ru': {
        'start_message_new': "Здравствуйте! 😃 \nВыберите нужный раздел:",
        'start_message_returning': "Выберите нужный раздел:",
        'choose_language': "Пожалуйста, выберите язык:",
        'income': "⬇️Доход",
        'expense': "⬆️Расход",
        'report': "🔄Отчет",
        'settings': "⚙️Параметр",
        'enter_income_amount': "💴 Введите сумму дохода:",
        'enter_expense_amount': "💸 Введите сумму расхода:",
        'choose_currency': "💰 Выберите валюту:",
        'choose_category': "📂 Выберите категорию:",
        'enter_comment': "💬 Введите комментарий:",
        'data_saved': "✅Данные сохранены",
        'choose_report': "Какой отчет вы хотите посмотреть?",
        'weekly': "Еженедельный",
        'monthly': "Ежемесячный",
        'view_in_telegram': "📲Посмотреть в Telegram",
        'download': "💾Скачать",
        'report_sent': "✅Отчет отправлен",
        'operation_cancelled': "❌Операция отменена.",
        'incorrect_selection': "Неправильный выбор.",
        'error_generating_report': "Произошла ошибка при создании отчета.",
        'cancel': "❌Отмена",
        'change_language': "Изменить язык",
        'select_language': "Сделайте выбор:",
        'invalid_amount': "Пожалуйста, введите корректную сумму:",
        'no_data': "Данные для отчета не найдены.",
        'expense_categories': [
            ('🩺 Здравоохранение', 'Здравоохранение'),
            ('🏖️ Отдых', 'Отдых'),
            ('💡 Коммунальные услуги', 'Коммунальные услуги'),
            ('💳 Кредит', 'Кредит'),
            ('🍽️ Питание', 'Питание'),
            ('🎓 Образование', 'Образование'),
            ('🎁 Подарки', 'Подарки'),
            ('🛒 Продукты', 'Продукты'),
            ('👨‍👩‍👧‍👦 Для семьи', 'Для семьи'),
            ('🏅 Спорт', 'Спорт'),
            ('🚗 Транспорт', 'Транспорт'),
            ('🔧 Другое', 'Другое'),
        ],
        'income_categories': [
            ('💵 Зарплата', 'Зарплата'),
            ('🎁 Подарок', 'Подарок'),
            ('🏦 Депозитные проценты', 'Депозитные проценты'),
            ('🔧 Другое', 'Другое'),
        ],
        # Новые добавленные тексты
        'family_budget': "👨‍👩‍👧‍👦 Семейный бюджет",
        'register_family': "👨‍👩‍👧‍👦 Создать семью",
        'join_family': "👥 Присоединиться к семье",
        'family_member': "👤 Член семьи",
        'approve_expense': "✅ Одобрить расход",
        'reject_expense': "❌ Отклонить расход",
        'expense_approved': "✅ Расход одобрен",
        'expense_rejected': "❌ Расход отклонен",
        'request_sent': "✅ Запрос отправлен, ожидайте одобрения главы семьи.",
        'set_budget': "💰 Установить бюджет",
        'enter_budget_amount': "💰 Введите сумму бюджета:",
        'budget_set': "✅ Бюджет установлен",
        'insufficient_budget': "❌ Недостаточно бюджета.",
        'graph_report': "📊 Графический отчет",
        'select_graph_type': "Выберите тип графика:",
        'income_expense_over_time': "📈 Доходы/Расходы по времени",
        'category_distribution': "📊 Распределение по категориям",
    },
}
